default:
	@echo "Compiling..."
	g++ -o ./server main.cpp core/*.cpp
	@echo "Compiled"
	@echo "Start"
	@./server
	@echo "End."

client: 
	@echo "Compiling..."
	g++ -o ./server ./client_test.cpp core/*.cpp
	@echo "Compiled"
	@echo "Start Client"
	@./server
	@echo "End."
	
